# curl 'http://localhost:3000/api/kanban'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:3000'
#  -H 'Referer: http://localhost:3000/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36'
#  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --data-raw '{"task":"bla","description":"bla","status":"OPEN"}'
#  --compressed
POST http://localhost:3000/api/kanban
Accept: application/json, text/plain, */*
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Content-Type: application/json

{
  "task": "Blub",
  "description": "Peter",
  "status": "IN_PROGRESS"
}

###

